"""Configuration constants for the AML alert prioritization system."""
from __future__ import annotations

from typing import Dict, List, Tuple

# Strict post-detection behavioral overlay: no transaction-level detection.
OVERLAY_MODE: bool = True

PAGE_TITLE: str = "AML Alert Prioritization"
PAGE_ICON: str = "🏦"
PAGE_LAYOUT: str = "wide"
PAGE_SIDEBAR_STATE: str = "expanded"

FEATURE_COLUMNS: List[str] = [
    "amount_rz",
    "velocity_rz",
    "activity_rz",
    "amount_z",
    "velocity_z",
    "activity_z",
]

BASELINE_WINDOW_DAYS: int = 30
BASELINE_MIN_USER_HIST: int = 20
BASELINE_MIN_SEGMENT_HIST: int = 200
BASELINE_EWMA_ALPHA: float = 0.15
BASELINE_ROBUST_EPS: float = 1e-9
MIN_USER_HISTORY: int = 12
MIN_SEG_HISTORY: int = 50
EPS: float = 1e-9
TIME_COL_CANDIDATES: List[str] = ["timestamp", "event_time", "tx_time", "datetime", "created_at"]

MIN_HISTORY: int = 12
WINSOR_P: Tuple[float, float] = (0.005, 0.995)
ROLL_WINDOW: int = 5

SYNTH_STRUCTURING_RATIO: float = 0.08
SYNTH_DORMANT_RATIO: float = 0.05
SYNTH_RAPID_WITHDRAW_RATIO: float = 0.06
SYNTH_FLOW_THROUGH_RATIO: float = 0.05
SYNTH_LOW_BUYER_RATIO: float = 0.04
SYNTH_HIGH_RISK_COUNTRY_RATIO: float = 0.07

STRUCTURING_THRESHOLD: int = 10000
STRUCTURING_LOW: int = 9500
STRUCTURING_WINDOW_DAYS: int = 60
STRUCTURING_COUNT_MIN: int = 3

DORMANT_INACTIVE_DAYS: int = 30
DORMANT_BURST_MIN: int = 8

RAPID_WITHDRAW_MINUTES: int = 30

FLOW_THROUGH_WINDOW_DAYS: int = 7
FLOW_THROUGH_RATIO_MIN: float = 0.90
FLOW_THROUGH_VOLUME_MIN: int = 5000

LOW_BUYERS_WINDOW_DAYS: int = 7
LOW_BUYERS_TX_MIN: int = 20
LOW_BUYERS_UNIQUE_MAX: int = 3

HIGH_RISK_COUNTRIES: List[str] = ["AE", "TR", "PA", "CY", "RU"]

# IDs and statuses
ALERT_ID_PREFIX: str = "ALERT_"
ALERT_ID_PAD: int = 6
CASE_ID_PREFIX: str = "CASE_"
CASE_ID_PAD: int = 5

# Canonical FSM (Phase E)
CASE_STATES: List[str] = ["OPEN", "ASSIGNED", "ESCALATED", "CLOSED_TP", "CLOSED_FP", "REOPENED"]
TERMINAL_STATES: List[str] = ["CLOSED_TP", "CLOSED_FP"]
ALLOWED_CASE_TRANSITIONS: Dict[str, List[str]] = {
    "OPEN": ["ASSIGNED", "ESCALATED", "CLOSED_TP", "CLOSED_FP"],
    "ASSIGNED": ["ESCALATED", "CLOSED_TP", "CLOSED_FP"],
    "ESCALATED": ["CLOSED_TP", "CLOSED_FP"],
    "CLOSED_TP": ["REOPENED"],
    "CLOSED_FP": ["REOPENED"],
    "REOPENED": ["ASSIGNED", "ESCALATED", "CLOSED_TP", "CLOSED_FP"],
}

# Backward-compat aliases (OPEN = NEW for display)
CASE_STATUS_NEW: str = "OPEN"
CASE_STATUS_ASSIGNED: str = "ASSIGNED"
CASE_STATUS_IN_CASE: str = "IN_CASE"
CASE_STATUS_ESCALATED: str = "ESCALATED"
CASE_STATUS_CLOSED_TP: str = "CLOSED_TP"
CASE_STATUS_CLOSED_FP: str = "CLOSED_FP"

CASE_ASSIGNED_DEFAULT: str = "Unassigned"
CASE_ACTOR_DEFAULT: str = "Analyst_1"

# Case Management Hardening
CASE_LOCK_TTL_SECONDS: int = 120  # Lock expires after 120 seconds

# -- Outcome Label Infrastructure ------------------------------------------
# Analyst disposition values written when a case is closed
OUTCOME_LABEL_SAR_FILED: str      = "SAR_FILED"    # True Positive: SAR submitted
OUTCOME_LABEL_TRUE_POSITIVE: str  = "TP"           # True Positive: confirmed suspicious
OUTCOME_LABEL_FALSE_POSITIVE: str = "FP"           # False Positive: not suspicious
OUTCOME_LABEL_INCONCLUSIVE: str   = "INCONCLUSIVE" # Analyst could not determine
OUTCOME_LABEL_PENDING: str        = "PENDING"      # Not yet reviewed

# Column name where analyst writes the disposition
OUTCOME_COLUMN: str = "analyst_disposition"

# Legacy synthetic label column (demo/dev only — not valid for production metrics)
SYNTHETIC_LABEL_COLUMN: str = "synthetic_true_suspicious"
SYNTHETIC_LABEL_WARNING: str = (
    "WARNING: synthetic_true_suspicious is a demo label generated by rule logic. "
    "It is NOT a valid ground truth for production evaluation. "
    "Connect real analyst disposition data via the OUTCOME_COLUMN pipeline."
)

# Minimum number of closed cases required before metrics are meaningful
MIN_CLOSED_CASES_FOR_METRICS: int = 50

# Analyst capacity defaults
DEFAULT_ANALYST_CAPACITY: int   = 50   # alerts per analyst per day
DEFAULT_MINUTES_PER_CASE: int   = 45   # minutes per investigation
DEFAULT_ANALYSTS_COUNT: int     = 10   # headcount
# ---------------------------------------------------------------------------

# Risk labels and thresholds
RISK_LABEL_YES: str = "Yes"
RISK_LABEL_NO: str = "No"
RISK_SCORE_THRESHOLD: int = 70
RISK_PROBA_THRESHOLD: float = 0.7
RISK_W_ML: float = 0.70
RISK_W_RULES: float = 0.30
RISK_BUCKET_LOW_MAX: int = 40
RISK_BUCKET_MED_MAX: int = 70
# Band thresholds (LOW < t1, MEDIUM < t2, HIGH < t3, else CRITICAL); used by canonical compute_risk
RISK_BAND_T1: int = 40   # LOW if score < t1
RISK_BAND_T2: int = 70   # MEDIUM if score < t2
RISK_BAND_T3: int = 90   # HIGH if score < t3, else CRITICAL
# =============================================================================
# SINGLE SOURCE OF TRUTH FOR ALL RISK WEIGHTS.
# Never hardcode these values anywhere else — always import from this module.
# =============================================================================
RISK_RULE_WEIGHT: float = 0.25
RISK_BEHAVIORAL_WEIGHT: float = 0.35
RISK_STRUCTURAL_WEIGHT: float = 0.15
RISK_TEMPORAL_ML_WEIGHT: float = 0.25
# Enforce that risk component weights sum to 1.0
assert abs(
    RISK_RULE_WEIGHT + RISK_BEHAVIORAL_WEIGHT +
    RISK_STRUCTURAL_WEIGHT + RISK_TEMPORAL_ML_WEIGHT - 1.0
) < 0.001, (
    f"Risk weights must sum to 1.0, got "
    f"{RISK_RULE_WEIGHT + RISK_BEHAVIORAL_WEIGHT + RISK_STRUCTURAL_WEIGHT + RISK_TEMPORAL_ML_WEIGHT}"
)
RISK_SIGMOID_TEMP: float = 1.6
RISK_WINSOR_PCT: float = 0.005
MAX_TRAIN_ROWS: int = 50000

# Explainability thresholds
EXPLAIN_RATIO_THRESHOLD: float = 2
EXPLAIN_Z_THRESHOLD: float = 2

# Model configuration
ANOMALY_CONTAMINATION: float = 0.05
ANOMALY_RANDOM_STATE: int = 42

RF_N_ESTIMATORS: int = 200
RF_MAX_DEPTH: int = 8
RF_RANDOM_STATE: int = 42
RF_CLASS_WEIGHT: str = "balanced_subsample"

TRAIN_TEST_SIZE: float = 0.25
TRAIN_TEST_RANDOM_STATE: int = 42

# AI model
GEMINI_MODEL_NAME: str = "gemini-2.5-flash"

# Demo data defaults
DEMO_DEFAULT_USERS: int = 80
DEMO_DEFAULT_TX_PER_USER: int = 40
DEMO_SEED: int = 42
DEMO_DEFAULT_SUSPICIOUS_RATE: float = 0.06

# Pilot test mode: risk-stratified synthetic alerts for overlay pilot evaluation.
# When True, after base alert generation, inject contextual risk signals to hit target distribution.
# Injection is deterministic and seeded by DEMO_SEED; dataset_hash remains reproducible.
PILOT_TEST_MODE: bool = True
PILOT_RISK_DISTRIBUTION: Dict[str, float] = {
    "low": 0.6,
    "medium": 0.25,
    "high": 0.12,
    "critical": 0.03,
}

DEMO_SEGMENTS: List[Tuple[str, Dict[str, float]]] = [
    ("retail_low", {"amount_mu": 40, "amount_sigma": 0.25, "gap_mu": 3.5, "gap_sigma": 0.35, "lam": 2}),
    ("retail_high", {"amount_mu": 120, "amount_sigma": 0.30, "gap_mu": 2.2, "gap_sigma": 0.35, "lam": 3}),
    ("smb", {"amount_mu": 350, "amount_sigma": 0.35, "gap_mu": 1.8, "gap_sigma": 0.40, "lam": 4}),
    ("corporate", {"amount_mu": 900, "amount_sigma": 0.30, "gap_mu": 1.5, "gap_sigma": 0.35, "lam": 5}),
]
DEMO_SEGMENT_PROBS: List[float] = [0.45, 0.30, 0.20, 0.05]

DEMO_TYPOLOGIES: List[str] = ["high_amount_outlier", "burst_activity", "smurfing", "rapid_velocity"]
DEMO_TYPOLOGY_PROBS: List[float] = [0.35, 0.25, 0.25, 0.15]

DEMO_BASE_AMOUNT_MIN: float = 5
DEMO_BASE_GAP_MIN: float = 0.05
DEMO_TIME_GAP_EPS: float = 0.01
DEMO_NUM_TX_ADD: int = 1

DEMO_AMOUNT_CLIP_MIN: float = 0.01
DEMO_AMOUNT_ROUND: int = 2
DEMO_TIME_GAP_CLIP_MIN: float = 0.01
DEMO_TIME_GAP_ROUND: int = 4

HIGH_AMOUNT_OUTLIER_MULTIPLIER_MIN: int = 10
HIGH_AMOUNT_OUTLIER_MULTIPLIER_MAX: int = 60

BURST_ACTIVITY_TX_ADD_MIN: int = 15
BURST_ACTIVITY_TX_ADD_MAX: int = 45
BURST_ACTIVITY_GAP_MULT_MIN: float = 0.15
BURST_ACTIVITY_GAP_MULT_MAX: float = 0.45

SMURFING_TX_ADD_MIN: int = 20
SMURFING_TX_ADD_MAX: int = 60
SMURFING_AMOUNT_MULT_MIN: float = 0.8
SMURFING_AMOUNT_MULT_MAX: float = 1.6
SMURFING_GAP_MULT_MIN: float = 0.10
SMURFING_GAP_MULT_MAX: float = 0.30

RAPID_VELOCITY_GAP_MULT_MIN: float = 0.03
RAPID_VELOCITY_GAP_MULT_MAX: float = 0.12
RAPID_VELOCITY_TX_ADD_MIN: int = 10
RAPID_VELOCITY_TX_ADD_MAX: int = 25

DEFAULT_SEGMENT: str = "unknown"
DEFAULT_TYPOLOGY: str = "none"
DEFAULT_SYNTHETIC_SUSPICIOUS: str = "No"

REQUIRED_CSV_COLUMNS: List[str] = ["amount", "time_gap", "num_transactions"]

# UI limits
DEMO_ROWS_MIN: int = 100
DEMO_ROWS_MAX: int = 2000
DEMO_ROWS_DEFAULT: int = 400
DEMO_ROWS_STEP: int = 100

MIN_RISK_MIN: int = 0
MIN_RISK_MAX: int = 100
MIN_RISK_DEFAULT: int = 70

ALERT_QUEUE_HEAD: int = 50
ALERT_QUEUE_HEIGHT: int = 420

USER_HISTORY_HEAD: int = 20
USER_HISTORY_HEIGHT: int = 320

AUDIT_LOG_HEIGHT: int = 240

DEBUG: bool = False

ANALYST_CAPACITY_MIN: int = 10
ANALYST_CAPACITY_MAX: int = 300
ANALYST_CAPACITY_DEFAULT: int = 50
ANALYST_CAPACITY_STEP: int = 10

MINUTES_PER_CASE_MIN: int = 2
MINUTES_PER_CASE_MAX: int = 60
MINUTES_PER_CASE_DEFAULT: int = 10
MINUTES_PER_CASE_STEP: int = 1

# Suppression layer configuration
RISK_QUEUE_MIN_SCORE: int = 70
MAX_ALERTS_PER_USER: int = 5
MAX_ALERTS_PER_USER_PER_SIGNATURE: int = 2
SEGMENT_MAX_SHARE: float = 0.55
SEGMENT_KEEP_PERCENT: float = 0.35

# Alert Governance Suppression Configuration
SUPPRESS_AMOUNT_DEV_THRESHOLD: float = 1.5
SUPPRESS_VELOCITY_DEV_THRESHOLD: float = 1.5
SUPPRESS_ACTIVITY_DEV_THRESHOLD: float = 1.5
SUPPRESS_RISK_SEGMENT_CAP: int = 75
SUPPRESS_RISK_HARD_CAP: int = 85
SUPPRESSION_DECISION_THRESHOLD: float = 0.5
FP_SUPPRESSION_RATIO: float = 0.7
HIGH_VOLUME_SEGMENTS: List[str] = ["retail_low", "retail_high"]
BENIGN_TYPOLOGIES: List[str] = ["salary_pattern", "merchant_settlement", "recurring_subscription"]

# Risk Stabilization Configuration
VOLATILITY_WEIGHT: float = 0.2
DAMPENING_EXPONENT: float = 0.85
WEIGHT_DAMPENED: float = 0.5
WEIGHT_BEHAVIORAL: float = 0.3
WEIGHT_CONSENSUS: float = 0.2
HIGH_RISK_OVERRIDE: int = 90

# Alert Governance Configuration
DAILY_ALERT_BUDGET: int = 400
PER_USER_DAILY_CAP: int = 3
DEDUP_WINDOW_DAYS: int = 7
MIN_RISK_FOR_QUEUE: int = 60

# Versioned governance policy (used when DB has no policy for this version)
CURRENT_POLICY_VERSION: str = "1.0"
# Segment-level throttling (policy params)
MAX_SHARE_PER_SEGMENT: float = 0.4  # No segment exceeds this share of daily budget
MIN_SHARE_FOR_HIGH_RISK_SEGMENTS: float = 0.0  # Optional floor for high-risk segments

# Bank-Grade Rule Engine Weights
RULE_WEIGHT_R001: float = 0.30  # Structuring
RULE_WEIGHT_R002: float = 0.20  # Burst Activity
RULE_WEIGHT_R003: float = 0.20  # Dormant Reactivation
RULE_WEIGHT_R004: float = 0.15  # Flow-Through
RULE_WEIGHT_R005: float = 0.15  # High Risk Country

# Hybrid Risk Integration Weights
HYBRID_ML_WEIGHT: float = 0.70  # ML risk_score weight
HYBRID_RULE_WEIGHT: float = 0.30  # rule_score_total weight
HYBRID_OVERRIDE_THRESHOLD: float = 0.8  # Override threshold for rule_score_total

# Feature Debug Configuration
SHOW_FEATURE_DEBUG: bool = False  # Set to True to print temporal feature debug info

# Probability Calibration Configuration
CALIBRATION_METHOD: str = "isotonic"  # "isotonic" or "platt"
SCORE_MAPPING_KIND: str = "logit_stretch"  # "logit_stretch" or "rank_percentile"
SCORE_TEMPERATURE: float = 1.8  # Temperature for logit_stretch (1.6-2.2 range)
SHOW_SCORE_DEBUG: bool = False  # Set to True to print score distribution debug info

# Temporal Behavior Modeling Weights (Step 2C)
SHOW_TEMPORAL_DEBUG: bool = False  # Set to True to print temporal feature debug info

# Model Caching Configuration
MODEL_CACHE_ENABLED: bool = True  # Enable model artifact caching
FORCE_RETRAIN: bool = False  # Force retraining even if cache exists
MODEL_CACHE_DIR: str = "data/model_cache"  # Cache directory path

# =============================================================================
# Phase G: Model Health & Ops Monitoring Thresholds
# =============================================================================
# All thresholds are configurable. Change values here to adjust sensitivity.
# No code changes required to tune monitoring behavior.

# G2: Risk Distribution Monitor Thresholds
# Saturation: share of alerts with risk_score >= 95
HEALTH_MAX_SATURATION_RATE: float = 0.30  # RED if >= 30%
HEALTH_SATURATION_AMBER: float = 0.20  # AMBER if >= 20%

# Top bin share: max histogram bin share (clustering proxy)
HEALTH_MAX_TOPBIN_SHARE: float = 0.50  # RED if >= 50%
HEALTH_TOPBIN_AMBER: float = 0.40  # AMBER if >= 40%

# G3: Alert Rate Monitor Thresholds
# Z-score thresholds for volume anomalies
HEALTH_ALERT_RATE_MAX_Z: float = 3.0  # RED if |z| >= 3.0
HEALTH_ALERT_RATE_AMBER_Z: float = 2.0  # AMBER if |z| >= 2.0

# Percent change thresholds
HEALTH_ALERT_RATE_MAX_PCT_CHANGE: float = 0.50  # RED if |pct| >= 50%
HEALTH_ALERT_RATE_AMBER_PCT: float = 0.30  # AMBER if |pct| >= 30%

# G4: Drift Proxy Monitor (PSI) Thresholds
# PSI < 0.1: No change, 0.1-0.25: Moderate, > 0.25: Significant
HEALTH_PSI_RED: float = 0.25  # RED if PSI >= 0.25
HEALTH_PSI_AMBER: float = 0.10  # AMBER if PSI >= 0.10

# G5: Rule Hit Distribution Monitor Thresholds
# Percent change thresholds for rule hit rate spikes
HEALTH_RULE_HIT_MAX_PCT_CHANGE: float = 1.0  # RED if |pct| >= 100%
HEALTH_RULE_HIT_AMBER_PCT: float = 0.5  # AMBER if |pct| >= 50%

# Z-score thresholds for rule hit rate spikes
HEALTH_RULE_HIT_MAX_Z: float = 3.0  # RED if |z| >= 3.0
HEALTH_RULE_HIT_AMBER_Z: float = 2.0  # AMBER if |z| >= 2.0

# G6: Health Report Configuration
HEALTH_BASELINE_WINDOW_RUNS: int = 7  # Number of previous runs for baseline
