apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ConfigMap
      name: althea-config
    patch: |-
      - op: replace
        path: /data/ALTHEA_ENV
        value: production
      - op: replace
        path: /data/ALTHEA_ALLOW_SQLITE_IN_DEV
        value: "false"
      - op: replace
        path: /data/ALTHEA_WORKER_CONCURRENCY
        value: "8"
      - op: replace
        path: /data/ALTHEA_PIPELINE_BATCH_SIZE
        value: "50000"
  - target:
      kind: Deployment
      name: althea-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 4
  - target:
      kind: Deployment
      name: althea-worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 8
