apiVersion: v1
kind: ConfigMap
metadata:
  name: althea-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "althea-backend"
        metrics_path: /metrics
        static_configs:
          - targets: ["althea-backend:80"]
